// Tue Jan 13 2026 - Alex

use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Opcode {
    Unknown,
    ADR,
    ADRP,
    ADD,
    ADDS,
    SUB,
    SUBS,
    ADC,
    ADCS,
    SBC,
    SBCS,
    NEG,
    NEGS,
    CMP,
    CMN,
    AND,
    ANDS,
    ORR,
    ORN,
    EOR,
    EON,
    BIC,
    BICS,
    TST,
    MOV,
    MOVZ,
    MOVN,
    MOVK,
    MVN,
    LSL,
    LSR,
    ASR,
    ROR,
    SBFM,
    BFM,
    UBFM,
    EXTR,
    UXTB,
    UXTH,
    SXTB,
    SXTH,
    SXTW,
    B,
    BL,
    BR,
    BLR,
    RET,
    Bcc,
    CBZ,
    CBNZ,
    TBZ,
    TBNZ,
    SVC,
    HVC,
    SMC,
    BRK,
    HLT,
    NOP,
    MSR,
    MRS,
    LDR,
    LDRB,
    LDRH,
    LDRSB,
    LDRSH,
    LDRSW,
    STR,
    STRB,
    STRH,
    LDP,
    STP,
    LDXR,
    STXR,
    LDAR,
    LDAXR,
    STLR,
    STLXR,
    MUL,
    MADD,
    MSUB,
    MNEG,
    SMULL,
    SMADDL,
    SMSUBL,
    SMULH,
    UMULL,
    UMADDL,
    UMSUBL,
    UMULH,
    SDIV,
    UDIV,
    CSEL,
    CSINC,
    CSINV,
    CSNEG,
    CSET,
    CSETM,
    CINC,
    CINV,
    CNEG,
    CCMN,
    CCMP,
    CLZ,
    CLS,
    RBIT,
    REV,
    REV16,
    REV32,
    REV64,
    SIMD(u16),
    FMOV,
    FADD,
    FSUB,
    FMUL,
    FDIV,
    FNEG,
    FABS,
    FSQRT,
    FCMP,
    FCMPE,
    FCSEL,
    FCCMP,
    FCCMPE,
    FCVT,
    FCVTZS,
    FCVTZU,
    SCVTF,
    UCVTF,
    FRINT,
    FRINTN,
    FRINTP,
    FRINTM,
    FRINTZ,
    FRINTA,
    FRINTX,
    FRINTI,
    DMB,
    DSB,
    ISB,
    SEV,
    SEVL,
    WFE,
    WFI,
    YIELD,
    HINT,
    CLREX,
    PRFM,
    SYS,
    SYSL,
    IC,
    DC,
    AT,
    TLBI,
    LD1,
    LD2,
    LD3,
    LD4,
    ST1,
    ST2,
    ST3,
    ST4,
    TBL,
    TBX,
    ZIP1,
    ZIP2,
    UZP1,
    UZP2,
    TRN1,
    TRN2,
    EXT,
    DUP,
    INS,
    SMOV,
    UMOV,
    ADDV,
    SADDLV,
    UADDLV,
    SMAXV,
    SMINV,
    UMAXV,
    UMINV,
    FMAXV,
    FMINV,
    FMAXNMV,
    FMINNMV,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OpcodeClass {
    Unknown,
    DataProcessingImmediate,
    DataProcessingRegister,
    DataProcessing3Source,
    Branch,
    ConditionalBranch,
    CompareAndBranch,
    TestAndBranch,
    Exception,
    System,
    LoadStore,
    LoadStorePair,
    LoadStoreExclusive,
    SIMD,
    FloatingPoint,
    Barrier,
    Hint,
    Cache,
}

impl Opcode {
    pub fn mnemonic(self) -> &'static str {
        match self {
            Opcode::Unknown => "???",
            Opcode::ADR => "adr",
            Opcode::ADRP => "adrp",
            Opcode::ADD => "add",
            Opcode::ADDS => "adds",
            Opcode::SUB => "sub",
            Opcode::SUBS => "subs",
            Opcode::ADC => "adc",
            Opcode::ADCS => "adcs",
            Opcode::SBC => "sbc",
            Opcode::SBCS => "sbcs",
            Opcode::NEG => "neg",
            Opcode::NEGS => "negs",
            Opcode::CMP => "cmp",
            Opcode::CMN => "cmn",
            Opcode::AND => "and",
            Opcode::ANDS => "ands",
            Opcode::ORR => "orr",
            Opcode::ORN => "orn",
            Opcode::EOR => "eor",
            Opcode::EON => "eon",
            Opcode::BIC => "bic",
            Opcode::BICS => "bics",
            Opcode::TST => "tst",
            Opcode::MOV => "mov",
            Opcode::MOVZ => "movz",
            Opcode::MOVN => "movn",
            Opcode::MOVK => "movk",
            Opcode::MVN => "mvn",
            Opcode::LSL => "lsl",
            Opcode::LSR => "lsr",
            Opcode::ASR => "asr",
            Opcode::ROR => "ror",
            Opcode::SBFM => "sbfm",
            Opcode::BFM => "bfm",
            Opcode::UBFM => "ubfm",
            Opcode::EXTR => "extr",
            Opcode::UXTB => "uxtb",
            Opcode::UXTH => "uxth",
            Opcode::SXTB => "sxtb",
            Opcode::SXTH => "sxth",
            Opcode::SXTW => "sxtw",
            Opcode::B => "b",
            Opcode::BL => "bl",
            Opcode::BR => "br",
            Opcode::BLR => "blr",
            Opcode::RET => "ret",
            Opcode::Bcc => "b",
            Opcode::CBZ => "cbz",
            Opcode::CBNZ => "cbnz",
            Opcode::TBZ => "tbz",
            Opcode::TBNZ => "tbnz",
            Opcode::SVC => "svc",
            Opcode::HVC => "hvc",
            Opcode::SMC => "smc",
            Opcode::BRK => "brk",
            Opcode::HLT => "hlt",
            Opcode::NOP => "nop",
            Opcode::MSR => "msr",
            Opcode::MRS => "mrs",
            Opcode::LDR => "ldr",
            Opcode::LDRB => "ldrb",
            Opcode::LDRH => "ldrh",
            Opcode::LDRSB => "ldrsb",
            Opcode::LDRSH => "ldrsh",
            Opcode::LDRSW => "ldrsw",
            Opcode::STR => "str",
            Opcode::STRB => "strb",
            Opcode::STRH => "strh",
            Opcode::LDP => "ldp",
            Opcode::STP => "stp",
            Opcode::LDXR => "ldxr",
            Opcode::STXR => "stxr",
            Opcode::LDAR => "ldar",
            Opcode::LDAXR => "ldaxr",
            Opcode::STLR => "stlr",
            Opcode::STLXR => "stlxr",
            Opcode::MUL => "mul",
            Opcode::MADD => "madd",
            Opcode::MSUB => "msub",
            Opcode::MNEG => "mneg",
            Opcode::SMULL => "smull",
            Opcode::SMADDL => "smaddl",
            Opcode::SMSUBL => "smsubl",
            Opcode::SMULH => "smulh",
            Opcode::UMULL => "umull",
            Opcode::UMADDL => "umaddl",
            Opcode::UMSUBL => "umsubl",
            Opcode::UMULH => "umulh",
            Opcode::SDIV => "sdiv",
            Opcode::UDIV => "udiv",
            Opcode::CSEL => "csel",
            Opcode::CSINC => "csinc",
            Opcode::CSINV => "csinv",
            Opcode::CSNEG => "csneg",
            Opcode::CSET => "cset",
            Opcode::CSETM => "csetm",
            Opcode::CINC => "cinc",
            Opcode::CINV => "cinv",
            Opcode::CNEG => "cneg",
            Opcode::CCMN => "ccmn",
            Opcode::CCMP => "ccmp",
            Opcode::CLZ => "clz",
            Opcode::CLS => "cls",
            Opcode::RBIT => "rbit",
            Opcode::REV => "rev",
            Opcode::REV16 => "rev16",
            Opcode::REV32 => "rev32",
            Opcode::REV64 => "rev64",
            Opcode::SIMD(_) => "simd",
            Opcode::FMOV => "fmov",
            Opcode::FADD => "fadd",
            Opcode::FSUB => "fsub",
            Opcode::FMUL => "fmul",
            Opcode::FDIV => "fdiv",
            Opcode::FNEG => "fneg",
            Opcode::FABS => "fabs",
            Opcode::FSQRT => "fsqrt",
            Opcode::FCMP => "fcmp",
            Opcode::FCMPE => "fcmpe",
            Opcode::FCSEL => "fcsel",
            Opcode::FCCMP => "fccmp",
            Opcode::FCCMPE => "fccmpe",
            Opcode::FCVT => "fcvt",
            Opcode::FCVTZS => "fcvtzs",
            Opcode::FCVTZU => "fcvtzu",
            Opcode::SCVTF => "scvtf",
            Opcode::UCVTF => "ucvtf",
            Opcode::FRINT => "frint",
            Opcode::FRINTN => "frintn",
            Opcode::FRINTP => "frintp",
            Opcode::FRINTM => "frintm",
            Opcode::FRINTZ => "frintz",
            Opcode::FRINTA => "frinta",
            Opcode::FRINTX => "frintx",
            Opcode::FRINTI => "frinti",
            Opcode::DMB => "dmb",
            Opcode::DSB => "dsb",
            Opcode::ISB => "isb",
            Opcode::SEV => "sev",
            Opcode::SEVL => "sevl",
            Opcode::WFE => "wfe",
            Opcode::WFI => "wfi",
            Opcode::YIELD => "yield",
            Opcode::HINT => "hint",
            Opcode::CLREX => "clrex",
            Opcode::PRFM => "prfm",
            Opcode::SYS => "sys",
            Opcode::SYSL => "sysl",
            Opcode::IC => "ic",
            Opcode::DC => "dc",
            Opcode::AT => "at",
            Opcode::TLBI => "tlbi",
            Opcode::LD1 => "ld1",
            Opcode::LD2 => "ld2",
            Opcode::LD3 => "ld3",
            Opcode::LD4 => "ld4",
            Opcode::ST1 => "st1",
            Opcode::ST2 => "st2",
            Opcode::ST3 => "st3",
            Opcode::ST4 => "st4",
            Opcode::TBL => "tbl",
            Opcode::TBX => "tbx",
            Opcode::ZIP1 => "zip1",
            Opcode::ZIP2 => "zip2",
            Opcode::UZP1 => "uzp1",
            Opcode::UZP2 => "uzp2",
            Opcode::TRN1 => "trn1",
            Opcode::TRN2 => "trn2",
            Opcode::EXT => "ext",
            Opcode::DUP => "dup",
            Opcode::INS => "ins",
            Opcode::SMOV => "smov",
            Opcode::UMOV => "umov",
            Opcode::ADDV => "addv",
            Opcode::SADDLV => "saddlv",
            Opcode::UADDLV => "uaddlv",
            Opcode::SMAXV => "smaxv",
            Opcode::SMINV => "sminv",
            Opcode::UMAXV => "umaxv",
            Opcode::UMINV => "uminv",
            Opcode::FMAXV => "fmaxv",
            Opcode::FMINV => "fminv",
            Opcode::FMAXNMV => "fmaxnmv",
            Opcode::FMINNMV => "fminnmv",
        }
    }

    pub fn class(self) -> OpcodeClass {
        match self {
            Opcode::Unknown => OpcodeClass::Unknown,
            Opcode::ADR | Opcode::ADRP => OpcodeClass::DataProcessingImmediate,
            Opcode::ADD | Opcode::ADDS | Opcode::SUB | Opcode::SUBS |
            Opcode::ADC | Opcode::ADCS | Opcode::SBC | Opcode::SBCS |
            Opcode::NEG | Opcode::NEGS | Opcode::CMP | Opcode::CMN => OpcodeClass::DataProcessingImmediate,
            Opcode::AND | Opcode::ANDS | Opcode::ORR | Opcode::ORN |
            Opcode::EOR | Opcode::EON | Opcode::BIC | Opcode::BICS |
            Opcode::TST => OpcodeClass::DataProcessingRegister,
            Opcode::MOV | Opcode::MOVZ | Opcode::MOVN | Opcode::MOVK | Opcode::MVN => OpcodeClass::DataProcessingImmediate,
            Opcode::LSL | Opcode::LSR | Opcode::ASR | Opcode::ROR => OpcodeClass::DataProcessingRegister,
            Opcode::SBFM | Opcode::BFM | Opcode::UBFM | Opcode::EXTR => OpcodeClass::DataProcessingImmediate,
            Opcode::UXTB | Opcode::UXTH | Opcode::SXTB | Opcode::SXTH | Opcode::SXTW => OpcodeClass::DataProcessingImmediate,
            Opcode::B | Opcode::BL => OpcodeClass::Branch,
            Opcode::BR | Opcode::BLR | Opcode::RET => OpcodeClass::Branch,
            Opcode::Bcc => OpcodeClass::ConditionalBranch,
            Opcode::CBZ | Opcode::CBNZ => OpcodeClass::CompareAndBranch,
            Opcode::TBZ | Opcode::TBNZ => OpcodeClass::TestAndBranch,
            Opcode::SVC | Opcode::HVC | Opcode::SMC | Opcode::BRK | Opcode::HLT => OpcodeClass::Exception,
            Opcode::NOP | Opcode::MSR | Opcode::MRS => OpcodeClass::System,
            Opcode::LDR | Opcode::LDRB | Opcode::LDRH | Opcode::LDRSB |
            Opcode::LDRSH | Opcode::LDRSW | Opcode::STR | Opcode::STRB | Opcode::STRH => OpcodeClass::LoadStore,
            Opcode::LDP | Opcode::STP => OpcodeClass::LoadStorePair,
            Opcode::LDXR | Opcode::STXR | Opcode::LDAR | Opcode::LDAXR |
            Opcode::STLR | Opcode::STLXR => OpcodeClass::LoadStoreExclusive,
            Opcode::MUL | Opcode::MADD | Opcode::MSUB | Opcode::MNEG |
            Opcode::SMULL | Opcode::SMADDL | Opcode::SMSUBL | Opcode::SMULH |
            Opcode::UMULL | Opcode::UMADDL | Opcode::UMSUBL | Opcode::UMULH |
            Opcode::SDIV | Opcode::UDIV => OpcodeClass::DataProcessing3Source,
            Opcode::CSEL | Opcode::CSINC | Opcode::CSINV | Opcode::CSNEG |
            Opcode::CSET | Opcode::CSETM | Opcode::CINC | Opcode::CINV | Opcode::CNEG |
            Opcode::CCMN | Opcode::CCMP => OpcodeClass::DataProcessingRegister,
            Opcode::CLZ | Opcode::CLS | Opcode::RBIT | Opcode::REV |
            Opcode::REV16 | Opcode::REV32 | Opcode::REV64 => OpcodeClass::DataProcessingRegister,
            Opcode::SIMD(_) => OpcodeClass::SIMD,
            Opcode::FMOV | Opcode::FADD | Opcode::FSUB | Opcode::FMUL |
            Opcode::FDIV | Opcode::FNEG | Opcode::FABS | Opcode::FSQRT |
            Opcode::FCMP | Opcode::FCMPE | Opcode::FCSEL | Opcode::FCCMP | Opcode::FCCMPE |
            Opcode::FCVT | Opcode::FCVTZS | Opcode::FCVTZU | Opcode::SCVTF | Opcode::UCVTF |
            Opcode::FRINT | Opcode::FRINTN | Opcode::FRINTP | Opcode::FRINTM |
            Opcode::FRINTZ | Opcode::FRINTA | Opcode::FRINTX | Opcode::FRINTI => OpcodeClass::FloatingPoint,
            Opcode::DMB | Opcode::DSB | Opcode::ISB => OpcodeClass::Barrier,
            Opcode::SEV | Opcode::SEVL | Opcode::WFE | Opcode::WFI |
            Opcode::YIELD | Opcode::HINT | Opcode::CLREX => OpcodeClass::Hint,
            Opcode::PRFM | Opcode::SYS | Opcode::SYSL | Opcode::IC |
            Opcode::DC | Opcode::AT | Opcode::TLBI => OpcodeClass::Cache,
            Opcode::LD1 | Opcode::LD2 | Opcode::LD3 | Opcode::LD4 |
            Opcode::ST1 | Opcode::ST2 | Opcode::ST3 | Opcode::ST4 |
            Opcode::TBL | Opcode::TBX | Opcode::ZIP1 | Opcode::ZIP2 |
            Opcode::UZP1 | Opcode::UZP2 | Opcode::TRN1 | Opcode::TRN2 |
            Opcode::EXT | Opcode::DUP | Opcode::INS | Opcode::SMOV | Opcode::UMOV |
            Opcode::ADDV | Opcode::SADDLV | Opcode::UADDLV |
            Opcode::SMAXV | Opcode::SMINV | Opcode::UMAXV | Opcode::UMINV |
            Opcode::FMAXV | Opcode::FMINV | Opcode::FMAXNMV | Opcode::FMINNMV => OpcodeClass::SIMD,
        }
    }

    pub fn is_branch(self) -> bool {
        matches!(self.class(), OpcodeClass::Branch | OpcodeClass::ConditionalBranch | OpcodeClass::CompareAndBranch | OpcodeClass::TestAndBranch)
    }

    pub fn is_call(self) -> bool {
        matches!(self, Opcode::BL | Opcode::BLR)
    }

    pub fn is_return(self) -> bool {
        matches!(self, Opcode::RET)
    }

    pub fn is_conditional(self) -> bool {
        matches!(self.class(), OpcodeClass::ConditionalBranch | OpcodeClass::CompareAndBranch | OpcodeClass::TestAndBranch) ||
        matches!(self, Opcode::CSEL | Opcode::CSINC | Opcode::CSINV | Opcode::CSNEG |
            Opcode::CSET | Opcode::CSETM | Opcode::CINC | Opcode::CINV | Opcode::CNEG |
            Opcode::CCMN | Opcode::CCMP | Opcode::FCSEL | Opcode::FCCMP | Opcode::FCCMPE)
    }

    pub fn is_memory(self) -> bool {
        matches!(self.class(), OpcodeClass::LoadStore | OpcodeClass::LoadStorePair | OpcodeClass::LoadStoreExclusive)
    }

    pub fn is_load(self) -> bool {
        matches!(self, Opcode::LDR | Opcode::LDRB | Opcode::LDRH | Opcode::LDRSB |
            Opcode::LDRSH | Opcode::LDRSW | Opcode::LDP | Opcode::LDXR |
            Opcode::LDAR | Opcode::LDAXR)
    }

    pub fn is_store(self) -> bool {
        matches!(self, Opcode::STR | Opcode::STRB | Opcode::STRH | Opcode::STP |
            Opcode::STXR | Opcode::STLR | Opcode::STLXR)
    }

    pub fn sets_flags(self) -> bool {
        matches!(self, Opcode::ADDS | Opcode::SUBS | Opcode::ADCS | Opcode::SBCS |
            Opcode::NEGS | Opcode::ANDS | Opcode::BICS | Opcode::CMP | Opcode::CMN | Opcode::TST |
            Opcode::CCMN | Opcode::CCMP | Opcode::FCMP | Opcode::FCMPE | Opcode::FCCMP | Opcode::FCCMPE)
    }

    pub fn reads_flags(self) -> bool {
        matches!(self, Opcode::Bcc | Opcode::ADC | Opcode::ADCS | Opcode::SBC | Opcode::SBCS |
            Opcode::CSEL | Opcode::CSINC | Opcode::CSINV | Opcode::CSNEG |
            Opcode::CCMN | Opcode::CCMP | Opcode::FCSEL | Opcode::FCCMP | Opcode::FCCMPE)
    }
}

impl fmt::Display for Opcode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.mnemonic())
    }
}

pub fn parse_opcode(s: &str) -> Option<Opcode> {
    let s_lower = s.to_lowercase();
    match s_lower.as_str() {
        "adr" => Some(Opcode::ADR),
        "adrp" => Some(Opcode::ADRP),
        "add" => Some(Opcode::ADD),
        "adds" => Some(Opcode::ADDS),
        "sub" => Some(Opcode::SUB),
        "subs" => Some(Opcode::SUBS),
        "cmp" => Some(Opcode::CMP),
        "cmn" => Some(Opcode::CMN),
        "and" => Some(Opcode::AND),
        "ands" => Some(Opcode::ANDS),
        "orr" => Some(Opcode::ORR),
        "eor" => Some(Opcode::EOR),
        "tst" => Some(Opcode::TST),
        "mov" => Some(Opcode::MOV),
        "movz" => Some(Opcode::MOVZ),
        "movn" => Some(Opcode::MOVN),
        "movk" => Some(Opcode::MOVK),
        "mvn" => Some(Opcode::MVN),
        "lsl" => Some(Opcode::LSL),
        "lsr" => Some(Opcode::LSR),
        "asr" => Some(Opcode::ASR),
        "ror" => Some(Opcode::ROR),
        "b" => Some(Opcode::B),
        "bl" => Some(Opcode::BL),
        "br" => Some(Opcode::BR),
        "blr" => Some(Opcode::BLR),
        "ret" => Some(Opcode::RET),
        "cbz" => Some(Opcode::CBZ),
        "cbnz" => Some(Opcode::CBNZ),
        "tbz" => Some(Opcode::TBZ),
        "tbnz" => Some(Opcode::TBNZ),
        "svc" => Some(Opcode::SVC),
        "brk" => Some(Opcode::BRK),
        "nop" => Some(Opcode::NOP),
        "ldr" => Some(Opcode::LDR),
        "ldrb" => Some(Opcode::LDRB),
        "ldrh" => Some(Opcode::LDRH),
        "ldrsb" => Some(Opcode::LDRSB),
        "ldrsh" => Some(Opcode::LDRSH),
        "ldrsw" => Some(Opcode::LDRSW),
        "str" => Some(Opcode::STR),
        "strb" => Some(Opcode::STRB),
        "strh" => Some(Opcode::STRH),
        "ldp" => Some(Opcode::LDP),
        "stp" => Some(Opcode::STP),
        "mul" => Some(Opcode::MUL),
        "sdiv" => Some(Opcode::SDIV),
        "udiv" => Some(Opcode::UDIV),
        _ => None,
    }
}
