// Tue Jan 13 2026 - Alex

use crate::luau::bytecode::OpcodeFormat;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum LuauOpcode {
    Nop = 0,
    Break,
    LoadNil,
    LoadB,
    LoadN,
    LoadK,
    Move,
    GetGlobal,
    SetGlobal,
    GetUpval,
    SetUpval,
    CloseUpvals,
    GetImport,
    GetTable,
    SetTable,
    GetTableKs,
    SetTableKs,
    GetTableN,
    SetTableN,
    NewClosure,
    NameCall,
    Call,
    Return,
    Jump,
    JumpBack,
    JumpIf,
    JumpIfNot,
    JumpIfEq,
    JumpIfLe,
    JumpIfLt,
    JumpIfNotEq,
    JumpIfNotLe,
    JumpIfNotLt,
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    Pow,
    Addk,
    Subk,
    Mulk,
    Divk,
    Modk,
    Powk,
    And,
    Or,
    Andk,
    Ork,
    Concat,
    Not,
    Minus,
    Length,
    NewTable,
    DupTable,
    SetList,
    ForNPrep,
    ForNLoop,
    ForGPrep,
    ForGLoop,
    ForGPrepInext,
    ForGLoopInext,
    ForGPrepNext,
    ForGLoopNext,
    GetVarargs,
    DupClosure,
    PrepVarargs,
    LoadKx,
    JumpX,
    FastCall,
    Coverage,
    Capture,
    JumpIfConstant,
    JumpIfNotConstant,
    FastCall1,
    FastCall2,
    FastCall2K,
    ForGPrepXnext,
    ForGLoopXnext,
    Unknown(u8),
}

impl LuauOpcode {
    pub fn from_u8(value: u8) -> Self {
        match value {
            0 => LuauOpcode::Nop,
            1 => LuauOpcode::Break,
            2 => LuauOpcode::LoadNil,
            3 => LuauOpcode::LoadB,
            4 => LuauOpcode::LoadN,
            5 => LuauOpcode::LoadK,
            6 => LuauOpcode::Move,
            7 => LuauOpcode::GetGlobal,
            8 => LuauOpcode::SetGlobal,
            9 => LuauOpcode::GetUpval,
            10 => LuauOpcode::SetUpval,
            11 => LuauOpcode::CloseUpvals,
            12 => LuauOpcode::GetImport,
            13 => LuauOpcode::GetTable,
            14 => LuauOpcode::SetTable,
            15 => LuauOpcode::GetTableKs,
            16 => LuauOpcode::SetTableKs,
            17 => LuauOpcode::GetTableN,
            18 => LuauOpcode::SetTableN,
            19 => LuauOpcode::NewClosure,
            20 => LuauOpcode::NameCall,
            21 => LuauOpcode::Call,
            22 => LuauOpcode::Return,
            23 => LuauOpcode::Jump,
            24 => LuauOpcode::JumpBack,
            25 => LuauOpcode::JumpIf,
            26 => LuauOpcode::JumpIfNot,
            27 => LuauOpcode::JumpIfEq,
            28 => LuauOpcode::JumpIfLe,
            29 => LuauOpcode::JumpIfLt,
            30 => LuauOpcode::JumpIfNotEq,
            31 => LuauOpcode::JumpIfNotLe,
            32 => LuauOpcode::JumpIfNotLt,
            33 => LuauOpcode::Add,
            34 => LuauOpcode::Sub,
            35 => LuauOpcode::Mul,
            36 => LuauOpcode::Div,
            37 => LuauOpcode::Mod,
            38 => LuauOpcode::Pow,
            39 => LuauOpcode::Addk,
            40 => LuauOpcode::Subk,
            41 => LuauOpcode::Mulk,
            42 => LuauOpcode::Divk,
            43 => LuauOpcode::Modk,
            44 => LuauOpcode::Powk,
            45 => LuauOpcode::And,
            46 => LuauOpcode::Or,
            47 => LuauOpcode::Andk,
            48 => LuauOpcode::Ork,
            49 => LuauOpcode::Concat,
            50 => LuauOpcode::Not,
            51 => LuauOpcode::Minus,
            52 => LuauOpcode::Length,
            53 => LuauOpcode::NewTable,
            54 => LuauOpcode::DupTable,
            55 => LuauOpcode::SetList,
            56 => LuauOpcode::ForNPrep,
            57 => LuauOpcode::ForNLoop,
            58 => LuauOpcode::ForGPrep,
            59 => LuauOpcode::ForGLoop,
            60 => LuauOpcode::ForGPrepInext,
            61 => LuauOpcode::ForGLoopInext,
            62 => LuauOpcode::ForGPrepNext,
            63 => LuauOpcode::ForGLoopNext,
            64 => LuauOpcode::GetVarargs,
            65 => LuauOpcode::DupClosure,
            66 => LuauOpcode::PrepVarargs,
            67 => LuauOpcode::LoadKx,
            68 => LuauOpcode::JumpX,
            69 => LuauOpcode::FastCall,
            70 => LuauOpcode::Coverage,
            71 => LuauOpcode::Capture,
            72 => LuauOpcode::JumpIfConstant,
            73 => LuauOpcode::JumpIfNotConstant,
            74 => LuauOpcode::FastCall1,
            75 => LuauOpcode::FastCall2,
            76 => LuauOpcode::FastCall2K,
            77 => LuauOpcode::ForGPrepXnext,
            78 => LuauOpcode::ForGLoopXnext,
            _ => LuauOpcode::Unknown(value),
        }
    }

    pub fn to_u8(&self) -> u8 {
        match self {
            LuauOpcode::Nop => 0,
            LuauOpcode::Break => 1,
            LuauOpcode::LoadNil => 2,
            LuauOpcode::LoadB => 3,
            LuauOpcode::LoadN => 4,
            LuauOpcode::LoadK => 5,
            LuauOpcode::Move => 6,
            LuauOpcode::GetGlobal => 7,
            LuauOpcode::SetGlobal => 8,
            LuauOpcode::GetUpval => 9,
            LuauOpcode::SetUpval => 10,
            LuauOpcode::CloseUpvals => 11,
            LuauOpcode::GetImport => 12,
            LuauOpcode::GetTable => 13,
            LuauOpcode::SetTable => 14,
            LuauOpcode::GetTableKs => 15,
            LuauOpcode::SetTableKs => 16,
            LuauOpcode::GetTableN => 17,
            LuauOpcode::SetTableN => 18,
            LuauOpcode::NewClosure => 19,
            LuauOpcode::NameCall => 20,
            LuauOpcode::Call => 21,
            LuauOpcode::Return => 22,
            LuauOpcode::Jump => 23,
            LuauOpcode::JumpBack => 24,
            LuauOpcode::JumpIf => 25,
            LuauOpcode::JumpIfNot => 26,
            LuauOpcode::JumpIfEq => 27,
            LuauOpcode::JumpIfLe => 28,
            LuauOpcode::JumpIfLt => 29,
            LuauOpcode::JumpIfNotEq => 30,
            LuauOpcode::JumpIfNotLe => 31,
            LuauOpcode::JumpIfNotLt => 32,
            LuauOpcode::Add => 33,
            LuauOpcode::Sub => 34,
            LuauOpcode::Mul => 35,
            LuauOpcode::Div => 36,
            LuauOpcode::Mod => 37,
            LuauOpcode::Pow => 38,
            LuauOpcode::Addk => 39,
            LuauOpcode::Subk => 40,
            LuauOpcode::Mulk => 41,
            LuauOpcode::Divk => 42,
            LuauOpcode::Modk => 43,
            LuauOpcode::Powk => 44,
            LuauOpcode::And => 45,
            LuauOpcode::Or => 46,
            LuauOpcode::Andk => 47,
            LuauOpcode::Ork => 48,
            LuauOpcode::Concat => 49,
            LuauOpcode::Not => 50,
            LuauOpcode::Minus => 51,
            LuauOpcode::Length => 52,
            LuauOpcode::NewTable => 53,
            LuauOpcode::DupTable => 54,
            LuauOpcode::SetList => 55,
            LuauOpcode::ForNPrep => 56,
            LuauOpcode::ForNLoop => 57,
            LuauOpcode::ForGPrep => 58,
            LuauOpcode::ForGLoop => 59,
            LuauOpcode::ForGPrepInext => 60,
            LuauOpcode::ForGLoopInext => 61,
            LuauOpcode::ForGPrepNext => 62,
            LuauOpcode::ForGLoopNext => 63,
            LuauOpcode::GetVarargs => 64,
            LuauOpcode::DupClosure => 65,
            LuauOpcode::PrepVarargs => 66,
            LuauOpcode::LoadKx => 67,
            LuauOpcode::JumpX => 68,
            LuauOpcode::FastCall => 69,
            LuauOpcode::Coverage => 70,
            LuauOpcode::Capture => 71,
            LuauOpcode::JumpIfConstant => 72,
            LuauOpcode::JumpIfNotConstant => 73,
            LuauOpcode::FastCall1 => 74,
            LuauOpcode::FastCall2 => 75,
            LuauOpcode::FastCall2K => 76,
            LuauOpcode::ForGPrepXnext => 77,
            LuauOpcode::ForGLoopXnext => 78,
            LuauOpcode::Unknown(v) => *v,
        }
    }

    pub fn name(&self) -> &'static str {
        match self {
            LuauOpcode::Nop => "NOP",
            LuauOpcode::Break => "BREAK",
            LuauOpcode::LoadNil => "LOADNIL",
            LuauOpcode::LoadB => "LOADB",
            LuauOpcode::LoadN => "LOADN",
            LuauOpcode::LoadK => "LOADK",
            LuauOpcode::Move => "MOVE",
            LuauOpcode::GetGlobal => "GETGLOBAL",
            LuauOpcode::SetGlobal => "SETGLOBAL",
            LuauOpcode::GetUpval => "GETUPVAL",
            LuauOpcode::SetUpval => "SETUPVAL",
            LuauOpcode::CloseUpvals => "CLOSEUPVALS",
            LuauOpcode::GetImport => "GETIMPORT",
            LuauOpcode::GetTable => "GETTABLE",
            LuauOpcode::SetTable => "SETTABLE",
            LuauOpcode::GetTableKs => "GETTABLEKS",
            LuauOpcode::SetTableKs => "SETTABLEKS",
            LuauOpcode::GetTableN => "GETTABLEN",
            LuauOpcode::SetTableN => "SETTABLEN",
            LuauOpcode::NewClosure => "NEWCLOSURE",
            LuauOpcode::NameCall => "NAMECALL",
            LuauOpcode::Call => "CALL",
            LuauOpcode::Return => "RETURN",
            LuauOpcode::Jump => "JUMP",
            LuauOpcode::JumpBack => "JUMPBACK",
            LuauOpcode::JumpIf => "JUMPIF",
            LuauOpcode::JumpIfNot => "JUMPIFNOT",
            LuauOpcode::JumpIfEq => "JUMPIFEQ",
            LuauOpcode::JumpIfLe => "JUMPIFLE",
            LuauOpcode::JumpIfLt => "JUMPIFLT",
            LuauOpcode::JumpIfNotEq => "JUMPIFNOTEQ",
            LuauOpcode::JumpIfNotLe => "JUMPIFNOTLE",
            LuauOpcode::JumpIfNotLt => "JUMPIFNOTLT",
            LuauOpcode::Add => "ADD",
            LuauOpcode::Sub => "SUB",
            LuauOpcode::Mul => "MUL",
            LuauOpcode::Div => "DIV",
            LuauOpcode::Mod => "MOD",
            LuauOpcode::Pow => "POW",
            LuauOpcode::Addk => "ADDK",
            LuauOpcode::Subk => "SUBK",
            LuauOpcode::Mulk => "MULK",
            LuauOpcode::Divk => "DIVK",
            LuauOpcode::Modk => "MODK",
            LuauOpcode::Powk => "POWK",
            LuauOpcode::And => "AND",
            LuauOpcode::Or => "OR",
            LuauOpcode::Andk => "ANDK",
            LuauOpcode::Ork => "ORK",
            LuauOpcode::Concat => "CONCAT",
            LuauOpcode::Not => "NOT",
            LuauOpcode::Minus => "MINUS",
            LuauOpcode::Length => "LENGTH",
            LuauOpcode::NewTable => "NEWTABLE",
            LuauOpcode::DupTable => "DUPTABLE",
            LuauOpcode::SetList => "SETLIST",
            LuauOpcode::ForNPrep => "FORNPREP",
            LuauOpcode::ForNLoop => "FORNLOOP",
            LuauOpcode::ForGPrep => "FORGPREP",
            LuauOpcode::ForGLoop => "FORGLOOP",
            LuauOpcode::ForGPrepInext => "FORGPREPINEXT",
            LuauOpcode::ForGLoopInext => "FORGLOOPINEXT",
            LuauOpcode::ForGPrepNext => "FORGPREPNEXT",
            LuauOpcode::ForGLoopNext => "FORGLOOPNEXT",
            LuauOpcode::GetVarargs => "GETVARARGS",
            LuauOpcode::DupClosure => "DUPCLOSURE",
            LuauOpcode::PrepVarargs => "PREPVARARGS",
            LuauOpcode::LoadKx => "LOADKX",
            LuauOpcode::JumpX => "JUMPX",
            LuauOpcode::FastCall => "FASTCALL",
            LuauOpcode::Coverage => "COVERAGE",
            LuauOpcode::Capture => "CAPTURE",
            LuauOpcode::JumpIfConstant => "JUMPIFCONST",
            LuauOpcode::JumpIfNotConstant => "JUMPIFNOTCONST",
            LuauOpcode::FastCall1 => "FASTCALL1",
            LuauOpcode::FastCall2 => "FASTCALL2",
            LuauOpcode::FastCall2K => "FASTCALL2K",
            LuauOpcode::ForGPrepXnext => "FORGPREPXNEXT",
            LuauOpcode::ForGLoopXnext => "FORGLOOPXNEXT",
            LuauOpcode::Unknown(_) => "UNKNOWN",
        }
    }

    pub fn is_jump(&self) -> bool {
        matches!(self,
            LuauOpcode::Jump |
            LuauOpcode::JumpBack |
            LuauOpcode::JumpIf |
            LuauOpcode::JumpIfNot |
            LuauOpcode::JumpIfEq |
            LuauOpcode::JumpIfLe |
            LuauOpcode::JumpIfLt |
            LuauOpcode::JumpIfNotEq |
            LuauOpcode::JumpIfNotLe |
            LuauOpcode::JumpIfNotLt |
            LuauOpcode::JumpX |
            LuauOpcode::JumpIfConstant |
            LuauOpcode::JumpIfNotConstant
        )
    }

    pub fn is_conditional_jump(&self) -> bool {
        matches!(self,
            LuauOpcode::JumpIf |
            LuauOpcode::JumpIfNot |
            LuauOpcode::JumpIfEq |
            LuauOpcode::JumpIfLe |
            LuauOpcode::JumpIfLt |
            LuauOpcode::JumpIfNotEq |
            LuauOpcode::JumpIfNotLe |
            LuauOpcode::JumpIfNotLt |
            LuauOpcode::JumpIfConstant |
            LuauOpcode::JumpIfNotConstant
        )
    }

    pub fn is_call(&self) -> bool {
        matches!(self, LuauOpcode::Call | LuauOpcode::FastCall | LuauOpcode::FastCall1 | LuauOpcode::FastCall2 | LuauOpcode::FastCall2K)
    }

    pub fn is_return(&self) -> bool {
        matches!(self, LuauOpcode::Return)
    }

    pub fn has_aux(&self) -> bool {
        matches!(self,
            LuauOpcode::GetGlobal |
            LuauOpcode::SetGlobal |
            LuauOpcode::GetImport |
            LuauOpcode::GetTableKs |
            LuauOpcode::SetTableKs |
            LuauOpcode::NameCall |
            LuauOpcode::NewClosure |
            LuauOpcode::DupClosure |
            LuauOpcode::LoadKx |
            LuauOpcode::JumpX |
            LuauOpcode::FastCall
        )
    }
}

pub struct OpcodeInfo {
    pub name: &'static str,
    pub format: OpcodeFormat,
    pub description: &'static str,
    pub has_aux: bool,
}

impl OpcodeInfo {
    pub fn from_opcode(opcode: LuauOpcode) -> Self {
        match opcode {
            LuauOpcode::Nop => Self::new("NOP", OpcodeFormat::None, "No operation", false),
            LuauOpcode::Break => Self::new("BREAK", OpcodeFormat::None, "Breakpoint", false),
            LuauOpcode::LoadNil => Self::new("LOADNIL", OpcodeFormat::A, "Load nil into register", false),
            LuauOpcode::LoadB => Self::new("LOADB", OpcodeFormat::ABC, "Load boolean into register", false),
            LuauOpcode::LoadN => Self::new("LOADN", OpcodeFormat::AD, "Load number into register", false),
            LuauOpcode::LoadK => Self::new("LOADK", OpcodeFormat::AD, "Load constant into register", false),
            LuauOpcode::Move => Self::new("MOVE", OpcodeFormat::AB, "Move register to register", false),
            LuauOpcode::GetGlobal => Self::new("GETGLOBAL", OpcodeFormat::A, "Get global variable", true),
            LuauOpcode::SetGlobal => Self::new("SETGLOBAL", OpcodeFormat::A, "Set global variable", true),
            LuauOpcode::GetUpval => Self::new("GETUPVAL", OpcodeFormat::AB, "Get upvalue", false),
            LuauOpcode::SetUpval => Self::new("SETUPVAL", OpcodeFormat::AB, "Set upvalue", false),
            LuauOpcode::CloseUpvals => Self::new("CLOSEUPVALS", OpcodeFormat::A, "Close upvalues", false),
            LuauOpcode::GetImport => Self::new("GETIMPORT", OpcodeFormat::AD, "Get imported value", true),
            LuauOpcode::GetTable => Self::new("GETTABLE", OpcodeFormat::ABC, "Get table element", false),
            LuauOpcode::SetTable => Self::new("SETTABLE", OpcodeFormat::ABC, "Set table element", false),
            LuauOpcode::GetTableKs => Self::new("GETTABLEKS", OpcodeFormat::ABC, "Get table element (constant key)", true),
            LuauOpcode::SetTableKs => Self::new("SETTABLEKS", OpcodeFormat::ABC, "Set table element (constant key)", true),
            LuauOpcode::GetTableN => Self::new("GETTABLEN", OpcodeFormat::ABC, "Get table element (numeric key)", false),
            LuauOpcode::SetTableN => Self::new("SETTABLEN", OpcodeFormat::ABC, "Set table element (numeric key)", false),
            LuauOpcode::NewClosure => Self::new("NEWCLOSURE", OpcodeFormat::AD, "Create new closure", true),
            LuauOpcode::NameCall => Self::new("NAMECALL", OpcodeFormat::ABC, "Method call preparation", true),
            LuauOpcode::Call => Self::new("CALL", OpcodeFormat::ABC, "Function call", false),
            LuauOpcode::Return => Self::new("RETURN", OpcodeFormat::AB, "Return from function", false),
            LuauOpcode::Jump => Self::new("JUMP", OpcodeFormat::AD, "Unconditional jump", false),
            LuauOpcode::JumpBack => Self::new("JUMPBACK", OpcodeFormat::AD, "Jump backward", false),
            LuauOpcode::JumpIf => Self::new("JUMPIF", OpcodeFormat::AD, "Jump if true", false),
            LuauOpcode::JumpIfNot => Self::new("JUMPIFNOT", OpcodeFormat::AD, "Jump if false", false),
            LuauOpcode::JumpIfEq => Self::new("JUMPIFEQ", OpcodeFormat::AD, "Jump if equal", true),
            LuauOpcode::JumpIfLe => Self::new("JUMPIFLE", OpcodeFormat::AD, "Jump if less/equal", true),
            LuauOpcode::JumpIfLt => Self::new("JUMPIFLT", OpcodeFormat::AD, "Jump if less than", true),
            LuauOpcode::JumpIfNotEq => Self::new("JUMPIFNOTEQ", OpcodeFormat::AD, "Jump if not equal", true),
            LuauOpcode::JumpIfNotLe => Self::new("JUMPIFNOTLE", OpcodeFormat::AD, "Jump if not less/equal", true),
            LuauOpcode::JumpIfNotLt => Self::new("JUMPIFNOTLT", OpcodeFormat::AD, "Jump if not less than", true),
            LuauOpcode::Add => Self::new("ADD", OpcodeFormat::ABC, "Addition", false),
            LuauOpcode::Sub => Self::new("SUB", OpcodeFormat::ABC, "Subtraction", false),
            LuauOpcode::Mul => Self::new("MUL", OpcodeFormat::ABC, "Multiplication", false),
            LuauOpcode::Div => Self::new("DIV", OpcodeFormat::ABC, "Division", false),
            LuauOpcode::Mod => Self::new("MOD", OpcodeFormat::ABC, "Modulo", false),
            LuauOpcode::Pow => Self::new("POW", OpcodeFormat::ABC, "Power", false),
            LuauOpcode::Addk => Self::new("ADDK", OpcodeFormat::ABC, "Add constant", false),
            LuauOpcode::Subk => Self::new("SUBK", OpcodeFormat::ABC, "Subtract constant", false),
            LuauOpcode::Mulk => Self::new("MULK", OpcodeFormat::ABC, "Multiply by constant", false),
            LuauOpcode::Divk => Self::new("DIVK", OpcodeFormat::ABC, "Divide by constant", false),
            LuauOpcode::Modk => Self::new("MODK", OpcodeFormat::ABC, "Modulo with constant", false),
            LuauOpcode::Powk => Self::new("POWK", OpcodeFormat::ABC, "Power with constant", false),
            LuauOpcode::And => Self::new("AND", OpcodeFormat::ABC, "Logical AND", false),
            LuauOpcode::Or => Self::new("OR", OpcodeFormat::ABC, "Logical OR", false),
            LuauOpcode::Andk => Self::new("ANDK", OpcodeFormat::ABC, "AND with constant", false),
            LuauOpcode::Ork => Self::new("ORK", OpcodeFormat::ABC, "OR with constant", false),
            LuauOpcode::Concat => Self::new("CONCAT", OpcodeFormat::ABC, "String concatenation", false),
            LuauOpcode::Not => Self::new("NOT", OpcodeFormat::AB, "Logical NOT", false),
            LuauOpcode::Minus => Self::new("MINUS", OpcodeFormat::AB, "Unary minus", false),
            LuauOpcode::Length => Self::new("LENGTH", OpcodeFormat::AB, "Length operator", false),
            LuauOpcode::NewTable => Self::new("NEWTABLE", OpcodeFormat::AB, "Create new table", true),
            LuauOpcode::DupTable => Self::new("DUPTABLE", OpcodeFormat::AD, "Duplicate table template", false),
            LuauOpcode::SetList => Self::new("SETLIST", OpcodeFormat::ABC, "Set table elements", true),
            LuauOpcode::ForNPrep => Self::new("FORNPREP", OpcodeFormat::AD, "Numeric for preparation", false),
            LuauOpcode::ForNLoop => Self::new("FORNLOOP", OpcodeFormat::AD, "Numeric for loop", false),
            LuauOpcode::ForGPrep => Self::new("FORGPREP", OpcodeFormat::AD, "Generic for preparation", false),
            LuauOpcode::ForGLoop => Self::new("FORGLOOP", OpcodeFormat::AD, "Generic for loop", true),
            LuauOpcode::ForGPrepInext => Self::new("FORGPREPINEXT", OpcodeFormat::AD, "Generic for inext preparation", false),
            LuauOpcode::ForGLoopInext => Self::new("FORGLOOPINEXT", OpcodeFormat::AD, "Generic for inext loop", false),
            LuauOpcode::ForGPrepNext => Self::new("FORGPREPNEXT", OpcodeFormat::AD, "Generic for next preparation", false),
            LuauOpcode::ForGLoopNext => Self::new("FORGLOOPNEXT", OpcodeFormat::AD, "Generic for next loop", false),
            LuauOpcode::GetVarargs => Self::new("GETVARARGS", OpcodeFormat::AB, "Get varargs", false),
            LuauOpcode::DupClosure => Self::new("DUPCLOSURE", OpcodeFormat::AD, "Duplicate closure", true),
            LuauOpcode::PrepVarargs => Self::new("PREPVARARGS", OpcodeFormat::A, "Prepare varargs", false),
            LuauOpcode::LoadKx => Self::new("LOADKX", OpcodeFormat::A, "Load extended constant", true),
            LuauOpcode::JumpX => Self::new("JUMPX", OpcodeFormat::None, "Extended jump", true),
            LuauOpcode::FastCall => Self::new("FASTCALL", OpcodeFormat::A, "Fast builtin call", true),
            LuauOpcode::Coverage => Self::new("COVERAGE", OpcodeFormat::None, "Coverage tracking", true),
            LuauOpcode::Capture => Self::new("CAPTURE", OpcodeFormat::AB, "Capture upvalue", false),
            LuauOpcode::JumpIfConstant => Self::new("JUMPIFCONST", OpcodeFormat::AD, "Jump if constant true", true),
            LuauOpcode::JumpIfNotConstant => Self::new("JUMPIFNOTCONST", OpcodeFormat::AD, "Jump if constant false", true),
            LuauOpcode::FastCall1 => Self::new("FASTCALL1", OpcodeFormat::AB, "Fast call with 1 arg", false),
            LuauOpcode::FastCall2 => Self::new("FASTCALL2", OpcodeFormat::ABC, "Fast call with 2 args", true),
            LuauOpcode::FastCall2K => Self::new("FASTCALL2K", OpcodeFormat::ABC, "Fast call with constant", true),
            LuauOpcode::ForGPrepXnext => Self::new("FORGPREPXNEXT", OpcodeFormat::AD, "Generic for xnext prep", false),
            LuauOpcode::ForGLoopXnext => Self::new("FORGLOOPXNEXT", OpcodeFormat::AD, "Generic for xnext loop", false),
            LuauOpcode::Unknown(_) => Self::new("UNKNOWN", OpcodeFormat::None, "Unknown opcode", false),
        }
    }

    fn new(name: &'static str, format: OpcodeFormat, description: &'static str, has_aux: bool) -> Self {
        Self {
            name,
            format,
            description,
            has_aux,
        }
    }
}
